version: '3'
services:
  app_prod:
    container_name: app_prod
    build: .
    image: app_prod_image:01
    volumes:
      - ./dist:/app/dist
      - /app/node_modules
      - media_prod:/app/media
    ports:
      - "3001:3000"
    env_file:
      - .env.prod
    restart: always
    networks:
      - main
networks:
  main:
    driver: bridge
volumes:
  media_prod: