version: '3'
services:
  app_dev:
    container_name: app_dev
    build: .
    image: app_dev_image:01
    volumes:
      - ./dist:/app/dist
      - /app/node_modules
      - media:/app/media
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    restart: always
    networks:
      - main
networks:
  main:
    driver: bridge
volumes:
  media: